### PR TITLE
Added BoundingPolygons and Test Cases for same.  Left the old code al…

### PR DESCRIPTION
**Pull request by JimTyrrell**
…one for backwards compatbility

### CODE REVIEW

**Comment by JimTyrrell** [comment]
Added new class and a test case.

**Comment by sshaaf** [comment]
@JimTyrrell how should we pass the polygon points? ConfigMap?

**Comment by JimTyrrell** [comment]
Right now it is a array of an array of doubles.
These are LatLongs, I assume this structure will map nicely top some sort of JSON call, or whatever we discuss on my call with Andy tomorrow.

double waypointsSquare1[][] = {
				{34.26, -77.95},
				{34.26, -77.82},
				{34.20, -77.82},
				{34.20, -77.95}
				};

You can use the API to pass in any number of inclusion and exclusion polygons.  A polygon automatically connects the last point to the first completing the shape.

**Comment by JimTyrrell** [comment]
Exclusion and Inclusion Zones now are coded the same in respect to nulls, and added in another test case.

**Comment by JimTyrrell** [comment]
Updated to faclilate Longitudes or Latitudes can be first.

**Comment by JimTyrrell** [comment]
Added in Waypoint

**Comment by JimTyrrell** [comment]
Added in Waypoint Interface

**Pull request merged**
